# Lista de tickers populares para el buscador (S&P 500, NASDAQ 100, etc.)
# Formato: "Nombre de la empresa (TICKER)"

COMMON_TICKERS = [
    "Apple Inc. (AAPL)",
    "Microsoft Corp. (MSFT)",
    "NVIDIA Corp. (NVDA)",
    "Amazon.com Inc. (AMZN)",
    "Alphabet Inc. Class A (GOOGL)",
    "Meta Platforms Inc. (META)",
    "Tesla Inc. (TSLA)",
    "Berkshire Hathaway Inc. (BRK.B)",
    "Taiwan Semiconductor Mfg (TSM)",
    "Broadcom Inc. (AVGO)",
    "JPMorgan Chase & Co. (JPM)",
    "Eli Lilly and Co. (LLY)",
    "Visa Inc. (V)",
    "UnitedHealth Group Inc. (UNH)",
    "Mastercard Inc. (MA)",
    "Home Depot Inc. (HD)",
    "Johnson & Johnson (JNJ)",
    "Procter & Gamble Co. (PG)",
    "Costco Wholesale Corp. (COST)",
    "AbbVie Inc. (ABBV)",
    "Merck & Co. Inc. (MRK)",
    "Advanced Micro Devices (AMD)",
    "Netflix Inc. (NFLX)",
    "PepsiCo Inc. (PEP)",
    "Coca-Cola Co. (KO)",
    "Walmart Inc. (WMT)",
    "Bank of America Corp. (BAC)",
    "Chevron Corp. (CVX)",
    "Exxon Mobil Corp. (XOM)",
    "Adobe Inc. (ADBE)",
    "Salesforce Inc. (CRM)",
    "Walt Disney Co. (DIS)",
    "McDonald's Corp. (MCD)",
    "Cisco Systems Inc. (CSCO)",
    "Intel Corp. (INTC)",
    "Pfizer Inc. (PFE)",
    "Oracle Corp. (ORCL)",
    "Comcast Corp. (CMCSA)",
    "Nike Inc. (NKE)",
    "Verizon Communications (VZ)",
    "AT&T Inc. (T)",
    "Wells Fargo & Co. (WFC)",
    "Qualcomm Inc. (QCOM)",
    "Boeing Co. (BA)",
    "IBM (IBM)",
    "Honeywell International (HON)",
    "Amgen Inc. (AMGN)",
    "Starbucks Corp. (SBUX)",
    "Gilead Sciences Inc. (GILD)",
    "Intuit Inc. (INTU)",
    "Applied Materials Inc. (AMAT)",
    "Texas Instruments (TXN)",
    "Citigroup Inc. (C)",
    "Morgan Stanley (MS)",
    "Goldman Sachs Group (GS)",
    "PayPal Holdings (PYPL)",
    "Uber Technologies (UBER)",
    "Airbnb Inc. (ABNB)",
    "Palantir Technologies (PLTR)",
    "Snowflake Inc. (SNOW)",
    "Shopify Inc. (SHOP)",
    "Spotify Technology (SPOT)",
    "Block Inc. (SQ)",
    "Coinbase Global (COIN)",
    "Moderna Inc. (MRNA)",
    "Ford Motor Co. (F)",
    "General Motors Co. (GM)",
    "Rivian Automotive (RIVN)",
    "Lucid Group (LCID)",
    "NIO Inc. (NIO)",
    "Alibaba Group (BABA)",
    "JD.com Inc. (JD)",
    "Baidu Inc. (BIDU)",
    "Tencent Music (TME)",
    "Sony Group Corp. (SONY)",
    "Nintendo Co. Ltd (NTDOY)",
    "Toyota Motor Corp. (TM)",
    "Honda Motor Co. (HMC)",
    "Shell PLC (SHEL)",
    "BP PLC (BP)",
    "TotalEnergies SE (TTE)",
    "Rio Tinto (RIO)",
    "BHP Group (BHP)",
    "Vale SA (VALE)",
    "Freeport-McMoRan (FCX)",
    "Newmont Corp. (NEM)",
    "Barrick Gold (GOLD)"
]

def get_ticker_from_string(s):
    # Extrae "TSM" de "Taiwan Semiconductor (TSM)"
    try:
        return s.split("(")[-1].replace(")", "").strip()
    except:
        return s

COMMON_ETFS = [
    "SPDR S&P 500 ETF Trust (SPY)",
    "Vanguard S&P 500 ETF (VOO)",
    "Vanguard S&P 500 UCITS ETF (VUAG.L)",
    "Invesco QQQ Trust (QQQ)",
    "Vanguard Total Stock Market (VTI)",
    "iShares Core S&P 500 ETF (IVV)",
    "Vanguard FTSE Developed Markets (VEA)",
    "Vanguard Value ETF (VTV)",
    "Vanguard Growth ETF (VUG)",
    "iShares Core MSCI EAFE ETF (IEFA)",
    "Vanguard Total Bond Market (BND)",
    "SPDR Gold Shares (GLD)",
    "iShares Russell 2000 ETF (IWM)",
    "Vanguard Real Estate (VNQ)",
    "Schwab US Dividend Equity (SCHD)",
    "JPMorgan Equity Premium Income (JEPI)",
    "ARK Innovation ETF (ARKK)",
    "VanEck Semiconductor ETF (SMH)",
    "Energy Select Sector SPDR (XLE)",
    "Financial Select Sector SPDR (XLF)",
    "Technology Select Sector SPDR (XLK)"
]

COMMON_CRYPTO = [
    "Bitcoin (BTC-USD)",
    "Ethereum (ETH-USD)",
    "Solana (SOL-USD)",
    "Binance Coin (BNB-USD)",
    "XRP (XRP-USD)",
    "Cardano (ADA-USD)",
    "Avalanche (AVAX-USD)",
    "Dogecoin (DOGE-USD)",
    "Polkadot (DOT-USD)",
    "Tron (TRX-USD)",
    "Chainlink (LINK-USD)",
    "Polygon (MATIC-USD)",
    "Shiba Inu (SHIB-USD)",
    "Litecoin (LTC-USD)",
    "Bitcoin Cash (BCH-USD)",
    "Stellar (XLM-USD)",
    "Monero (XMR-USD)",
    "Cosmos (ATOM-USD)",
    "Uniswap (UNI-USD)",
    "Near Protocol (NEAR-USD)"
]
